version: "3"

services:
    mpi_head:
        image: specfem3d-docker:latest
        ports:
          - "22"
        networks:
            - mpinet

    mpi_node:
        image: specfem3d-docker:latest
        deploy:
            replicas: 2
        networks:
            - mpinet

networks:
    mpinet:
